### ISSUE TITLE
QuickReduct

### ISSUE THREAD

**Issue by pddo** [4201715125/S4201715125V1#7]
Finish on commit bb1342b939166ab9cce62995e408e9bf48e050b4

**Comment by pddo** [comment]
Also temporarily fix InvalidOperationException by wrapping a `try catch` block  in function 
`public override IEnumerable<double?[]> LowerApproximation(Func<double?[], bool> fX)` 
of class
`StandardApproximationSpace`

**Root cause:**
Can't find any lower approx. class before unioning

**Comment by rexpan** [comment]
The bug has been fixed in issues #5.

@PDDo: Have we finished this function?

**Comment by pddo** [comment]
Have refined code of QuickReduct in commit b3018dd679499291d7bd93a6a427e98587fe879a and verify successful bug fixing in issue #5
